apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 22
      name: ssh
  selector:
    app: nginx
  externalIPs:
    - 10.0.0.6
