apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: nginx-ingress
data:
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-send-imeout: "600"
  body-size: "64m"
  server-name-hash-bucket-size: "256"
  server-tokens: "false"
